version: '3'
services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root

  psbs:
    container_name: psbs
    image: alexphillips/psbs
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=psbs
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=psbs
    ports:
      - 8080:80
