version: '3'
services:
  mariadb:
    image: linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=psbs

  psbs:
    image: sbs
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - DB_HOST=docker-bid-shift-scheduler_mariadb_1
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_DATABASE=psbs
    ports:
      - 8038:80
